
export const eliminationRules = [
  "Only tokens whose emoji + name character count forms a Fibonacci number survive",
  "Eliminate tokens where description contains more vowels than consonants",
  "Survive if token position multiplied by emoji Unicode value is prime",
  "Eliminate if token name anagram contains 'moon' or 'lambo'",
  "Only tokens whose holders count forms a perfect square survive",
  "Eliminate tokens where symbol length + emoji count equals holder count",
  "Survive if description contains exactly 3 punctuation marks",
  "Eliminate tokens whose name starts with the same letter as the most common first letter among all tokens",
  "Only tokens with palindrome total supply numbers survive",
  "Eliminate if token position + emoji Unicode value is divisible by 13",
  "Survive if description contains exactly two emoji references",
  "Eliminate tokens whose name contains same number of letters as current block height mod 10",
  "Only tokens whose holder count is a multiple of their position survive",
  "Eliminate if total supply divided by current supply is irrational",
  "Survive if token name contains exactly one mathematical symbol",
  "Eliminate tokens whose description has an odd number of words",
  "Only tokens with emoji from the 'food' category survive",
  "Eliminate if sum of ASCII values in symbol is prime",
  "Survive if token position is a perfect cube",
  "Eliminate tokens whose name contains more than one animal reference",
  "Only tokens whose description contains a movie quote survive",
  "Eliminate if total holder addresses contain more even numbers than odd",
  "Survive if token name contains exactly one color word",
  "Eliminate tokens whose symbol contains a repeated character",
  "Only tokens created during Mercury retrograde survive",
  "Eliminate if description contains any words from top 100 crypto buzzwords",
  "Survive if token position is divisible by both 3 and 7",
  "Eliminate tokens whose name length equals their position",
  "Only tokens with emoji that represent celestial bodies survive",
  "Eliminate if total supply is a palindrome",
  "Survive if description contains exactly three adjectives",
  "Eliminate tokens whose holder count is a Mersenne number",
  "Only tokens with name containing exactly two digits survive",
  "Eliminate if symbol contains any letter from 'HODL'",
  "Survive if token's creation timestamp is prime",
  "Eliminate tokens whose description contains 'safe' or 'moon'",
  "Only tokens with emoji from 'transportation' category survive",
  "Eliminate if total supply contains repeating digits",
  "Survive if token name contains a programming language",
  "Eliminate tokens whose symbol forms a valid English word",
  "Only tokens whose description contains exactly one meme reference survive",
  "Eliminate if holder count divided by position equals emoji Unicode value",
  "Survive if token name contains exactly one cryptocurrency reference",
  "Eliminate tokens whose description has perfect comma placement",
  "Only tokens with emoji representing extinct animals survive",
  "Eliminate if sum of all numbers in description is even",
  "Survive if token position is a triangular number",
  "Eliminate tokens whose name contains exactly two compound words",
  "Only tokens with emoji that change meaning when reversed survive",
  "Eliminate if description contains exactly three Oxford commas",
  "Only tokens with animal-themed emojis survive",
  "Eliminate tokens with more than 3 syllables in name",
  "Survive if description contains a haiku",
  "Eliminate tokens whose symbol contains a vowel",
  "Only tokens with food-related names survive",
  "Eliminate if total supply is not a multiple of 42",
  "Survive if emoji matches first letter of description",
  "Eliminate tokens created on odd-numbered days",
  "Only tokens with exactly 5 words in description survive",
  "Eliminate if holder count is less than position number",
  "Survive if token name contains alliteration",
  "Eliminate tokens whose symbol length is prime",
  "Only tokens with weather-related emojis survive",
  "Eliminate if description contains 'crypto' or 'token'",
  "Survive if total supply is a perfect power",
  "Eliminate tokens whose name ends in 'coin'",
  "Only tokens with emoji from 'nature' category survive",
  "Eliminate if holder count is a multiple of 7",
  "Survive if description contains a rhyming pair",
  "Eliminate tokens whose position is in bottom quartile",
  "Only tokens with single-character symbols survive",
  "Eliminate if name contains more than one number",
  "Survive if emoji is from 'faces' category",
  "Eliminate tokens whose description is shorter than name",
  "Only tokens with prime number of holders survive",
  "Eliminate if total supply contains digit '4'",
  "Survive if token name contains a planet name",
  "Eliminate tokens whose symbol contains numbers",
  "Only tokens with emoji representing tools survive",
  "Eliminate if description contains fewer than 10 words",
  "Top 10 tokens by holder count survive",
  "Tokens with total supply > 500M survive",
  "Tokens whose current supply is > 80% of total supply survive",
  "Tokens with description length > 100 characters survive",
  "Tokens with symbol length <= 4 survive",
  "Tokens whose name contains their symbol survive",
  "Top 15 tokens by creation date survive",
  "Tokens with unique first letter in name survive",
  "Tokens with highest holder-to-supply ratio survive",
  "Tokens in positions 1-10 survive",
  "Tokens with matching emoji category and name theme survive",
  "Tokens with descriptions containing their emoji survive",
  "Tokens whose symbol is all uppercase survive",
  "Tokens with balanced holder distribution (top holder < 10%) survive",
  "Tokens whose name length is less than 12 characters survive",
  "Tokens with unique emoji categories survive",
  "Tokens whose current supply differs less than 10% from total supply survive",
  "Tokens whose position is in top 50% survive",
  "Tokens with descriptive names (not random characters) survive",
  "Tokens whose holder count > 1% of total supply survive"];

  export const emojiList = ["🚀", "🌙", "🎮", "🎲", "🎪", "🎭", "🎨", "🎯", "🎪", "🎭", "🦄", "🐱", "🐶", "🦊", "🦁", "🐯", "🦒", "🦘", "🦬", "🦙", "🎪", "🎭", "🎨", "🃏", "🎲", "🎯", "🎪", "🎭"];
