blank_issues_enabled: true
contact_links:
  - name: Questions
    url: https://discord.com/channels/1220414409550336183/1304126107876069376
    about: Ask questions and discuss with other CDP community members
