"use client"
import { WagmiProvider } from "wagmi";
import "./globals.css";
import { ToastProvider } from "@radix-ui/react-toast";
import { config } from "./wagmi";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";


// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
const queryClient = new QueryClient()


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      >
        <WagmiProvider config={config}>
          <QueryClientProvider client={queryClient}>
          <ToastProvider>
            {children}
          </ToastProvider>
          </QueryClientProvider>
        </WagmiProvider>
      </body>
     </html>
  );
}
